/*
accent-auth

Accent's authentication service

API version: 0.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth

import (
	"encoding/json"
)

// checks if the ConfigPatchItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPatchItem{}

// ConfigPatchItem struct for ConfigPatchItem
type ConfigPatchItem struct {
	// Patch operation. Supported operations: `replace`.
	Op *string `json:"op,omitempty"`
	// JSON path to operate on. Supported paths: `/debug`.
	Path *string `json:"path,omitempty"`
	// The new value for the operation. Type of value is dependent of `path`
	Value map[string]interface{} `json:"value,omitempty"`
}

// NewConfigPatchItem instantiates a new ConfigPatchItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPatchItem() *ConfigPatchItem {
	this := ConfigPatchItem{}
	return &this
}

// NewConfigPatchItemWithDefaults instantiates a new ConfigPatchItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPatchItemWithDefaults() *ConfigPatchItem {
	this := ConfigPatchItem{}
	return &this
}

// GetOp returns the Op field value if set, zero value otherwise.
func (o *ConfigPatchItem) GetOp() string {
	if o == nil || IsNil(o.Op) {
		var ret string
		return ret
	}
	return *o.Op
}

// GetOpOk returns a tuple with the Op field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPatchItem) GetOpOk() (*string, bool) {
	if o == nil || IsNil(o.Op) {
		return nil, false
	}
	return o.Op, true
}

// HasOp returns a boolean if a field has been set.
func (o *ConfigPatchItem) HasOp() bool {
	if o != nil && !IsNil(o.Op) {
		return true
	}

	return false
}

// SetOp gets a reference to the given string and assigns it to the Op field.
func (o *ConfigPatchItem) SetOp(v string) {
	o.Op = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ConfigPatchItem) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPatchItem) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ConfigPatchItem) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ConfigPatchItem) SetPath(v string) {
	o.Path = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ConfigPatchItem) GetValue() map[string]interface{} {
	if o == nil || IsNil(o.Value) {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPatchItem) GetValueOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ConfigPatchItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *ConfigPatchItem) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o ConfigPatchItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPatchItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Op) {
		toSerialize["op"] = o.Op
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableConfigPatchItem struct {
	value *ConfigPatchItem
	isSet bool
}

func (v NullableConfigPatchItem) Get() *ConfigPatchItem {
	return v.value
}

func (v *NullableConfigPatchItem) Set(val *ConfigPatchItem) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPatchItem) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPatchItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPatchItem(val *ConfigPatchItem) *NullableConfigPatchItem {
	return &NullableConfigPatchItem{value: val, isSet: true}
}

func (v NullableConfigPatchItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPatchItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
