/*
accent-auth

Accent's authentication service

API version: 0.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExternalAuthUserList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalAuthUserList{}

// ExternalAuthUserList struct for ExternalAuthUserList
type ExternalAuthUserList struct {
	// The number of external auth matching the searched term.
	Filtered int32 `json:"filtered"`
	// A paginated list of connected external auth users
	Items []ExternalAuthUser `json:"items"`
	// The number of connected external auth users.
	Total int32 `json:"total"`
}

type _ExternalAuthUserList ExternalAuthUserList

// NewExternalAuthUserList instantiates a new ExternalAuthUserList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalAuthUserList(filtered int32, items []ExternalAuthUser, total int32) *ExternalAuthUserList {
	this := ExternalAuthUserList{}
	this.Filtered = filtered
	this.Items = items
	this.Total = total
	return &this
}

// NewExternalAuthUserListWithDefaults instantiates a new ExternalAuthUserList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalAuthUserListWithDefaults() *ExternalAuthUserList {
	this := ExternalAuthUserList{}
	return &this
}

// GetFiltered returns the Filtered field value
func (o *ExternalAuthUserList) GetFiltered() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Filtered
}

// GetFilteredOk returns a tuple with the Filtered field value
// and a boolean to check if the value has been set.
func (o *ExternalAuthUserList) GetFilteredOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filtered, true
}

// SetFiltered sets field value
func (o *ExternalAuthUserList) SetFiltered(v int32) {
	o.Filtered = v
}

// GetItems returns the Items field value
func (o *ExternalAuthUserList) GetItems() []ExternalAuthUser {
	if o == nil {
		var ret []ExternalAuthUser
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ExternalAuthUserList) GetItemsOk() ([]ExternalAuthUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ExternalAuthUserList) SetItems(v []ExternalAuthUser) {
	o.Items = v
}

// GetTotal returns the Total field value
func (o *ExternalAuthUserList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *ExternalAuthUserList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *ExternalAuthUserList) SetTotal(v int32) {
	o.Total = v
}

func (o ExternalAuthUserList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalAuthUserList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filtered"] = o.Filtered
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *ExternalAuthUserList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filtered",
		"items",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalAuthUserList := _ExternalAuthUserList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExternalAuthUserList)

	if err != nil {
		return err
	}

	*o = ExternalAuthUserList(varExternalAuthUserList)

	return err
}

type NullableExternalAuthUserList struct {
	value *ExternalAuthUserList
	isSet bool
}

func (v NullableExternalAuthUserList) Get() *ExternalAuthUserList {
	return v.value
}

func (v *NullableExternalAuthUserList) Set(val *ExternalAuthUserList) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalAuthUserList) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalAuthUserList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalAuthUserList(val *ExternalAuthUserList) *NullableExternalAuthUserList {
	return &NullableExternalAuthUserList{value: val, isSet: true}
}

func (v NullableExternalAuthUserList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalAuthUserList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
