/*
accent-auth

Accent's authentication service

API version: 0.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth

import (
	"encoding/json"
)

// checks if the RefreshTokenList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshTokenList{}

// RefreshTokenList struct for RefreshTokenList
type RefreshTokenList struct {
	// The number of refresh token matching the searched terms
	Filtered *int32 `json:"filtered,omitempty"`
	// A paginated list of refresh tokens
	Items []RefreshToken `json:"items,omitempty"`
	// The number of refresh tokens for that user
	Total *int32 `json:"total,omitempty"`
}

// NewRefreshTokenList instantiates a new RefreshTokenList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshTokenList() *RefreshTokenList {
	this := RefreshTokenList{}
	return &this
}

// NewRefreshTokenListWithDefaults instantiates a new RefreshTokenList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshTokenListWithDefaults() *RefreshTokenList {
	this := RefreshTokenList{}
	return &this
}

// GetFiltered returns the Filtered field value if set, zero value otherwise.
func (o *RefreshTokenList) GetFiltered() int32 {
	if o == nil || IsNil(o.Filtered) {
		var ret int32
		return ret
	}
	return *o.Filtered
}

// GetFilteredOk returns a tuple with the Filtered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshTokenList) GetFilteredOk() (*int32, bool) {
	if o == nil || IsNil(o.Filtered) {
		return nil, false
	}
	return o.Filtered, true
}

// HasFiltered returns a boolean if a field has been set.
func (o *RefreshTokenList) HasFiltered() bool {
	if o != nil && !IsNil(o.Filtered) {
		return true
	}

	return false
}

// SetFiltered gets a reference to the given int32 and assigns it to the Filtered field.
func (o *RefreshTokenList) SetFiltered(v int32) {
	o.Filtered = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *RefreshTokenList) GetItems() []RefreshToken {
	if o == nil || IsNil(o.Items) {
		var ret []RefreshToken
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshTokenList) GetItemsOk() ([]RefreshToken, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *RefreshTokenList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []RefreshToken and assigns it to the Items field.
func (o *RefreshTokenList) SetItems(v []RefreshToken) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *RefreshTokenList) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefreshTokenList) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *RefreshTokenList) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *RefreshTokenList) SetTotal(v int32) {
	o.Total = &v
}

func (o RefreshTokenList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshTokenList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filtered) {
		toSerialize["filtered"] = o.Filtered
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableRefreshTokenList struct {
	value *RefreshTokenList
	isSet bool
}

func (v NullableRefreshTokenList) Get() *RefreshTokenList {
	return v.value
}

func (v *NullableRefreshTokenList) Set(val *RefreshTokenList) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshTokenList) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshTokenList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshTokenList(val *RefreshTokenList) *NullableRefreshTokenList {
	return &NullableRefreshTokenList{value: val, isSet: true}
}

func (v NullableRefreshTokenList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshTokenList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
