/*
accent-auth

Accent's authentication service

API version: 0.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth

import (
	"encoding/json"
)

// checks if the TenantList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantList{}

// TenantList struct for TenantList
type TenantList struct {
	// The number of tenants matching the searched term
	Filtered *int32 `json:"filtered,omitempty"`
	// A paginated list of tenants
	Items []TenantResult `json:"items,omitempty"`
	// The number of tenants
	Total *int32 `json:"total,omitempty"`
}

// NewTenantList instantiates a new TenantList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantList() *TenantList {
	this := TenantList{}
	return &this
}

// NewTenantListWithDefaults instantiates a new TenantList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantListWithDefaults() *TenantList {
	this := TenantList{}
	return &this
}

// GetFiltered returns the Filtered field value if set, zero value otherwise.
func (o *TenantList) GetFiltered() int32 {
	if o == nil || IsNil(o.Filtered) {
		var ret int32
		return ret
	}
	return *o.Filtered
}

// GetFilteredOk returns a tuple with the Filtered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantList) GetFilteredOk() (*int32, bool) {
	if o == nil || IsNil(o.Filtered) {
		return nil, false
	}
	return o.Filtered, true
}

// HasFiltered returns a boolean if a field has been set.
func (o *TenantList) HasFiltered() bool {
	if o != nil && !IsNil(o.Filtered) {
		return true
	}

	return false
}

// SetFiltered gets a reference to the given int32 and assigns it to the Filtered field.
func (o *TenantList) SetFiltered(v int32) {
	o.Filtered = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *TenantList) GetItems() []TenantResult {
	if o == nil || IsNil(o.Items) {
		var ret []TenantResult
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantList) GetItemsOk() ([]TenantResult, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *TenantList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TenantResult and assigns it to the Items field.
func (o *TenantList) SetItems(v []TenantResult) {
	o.Items = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TenantList) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantList) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TenantList) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *TenantList) SetTotal(v int32) {
	o.Total = &v
}

func (o TenantList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filtered) {
		toSerialize["filtered"] = o.Filtered
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableTenantList struct {
	value *TenantList
	isSet bool
}

func (v NullableTenantList) Get() *TenantList {
	return v.value
}

func (v *NullableTenantList) Set(val *TenantList) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantList) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantList(val *TenantList) *NullableTenantList {
	return &NullableTenantList{value: val, isSet: true}
}

func (v NullableTenantList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
