/*
accent-auth

Accent's authentication service

API version: 0.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth

import (
	"encoding/json"
)

// checks if the TenantEdit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantEdit{}

// TenantEdit struct for TenantEdit
type TenantEdit struct {
	Address *TenantAddress `json:"address,omitempty"`
	// The contact user's UUID
	Contact *string `json:"contact,omitempty"`
	// A list containing human readeable unique domain names, associated with a specific tenant
	DomainNames []string `json:"domain_names,omitempty"`
	// The tenant's name
	Name *string `json:"name,omitempty"`
	// The tenant's contact phone number
	Phone *string `json:"phone,omitempty"`
}

// NewTenantEdit instantiates a new TenantEdit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantEdit() *TenantEdit {
	this := TenantEdit{}
	return &this
}

// NewTenantEditWithDefaults instantiates a new TenantEdit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantEditWithDefaults() *TenantEdit {
	this := TenantEdit{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *TenantEdit) GetAddress() TenantAddress {
	if o == nil || IsNil(o.Address) {
		var ret TenantAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantEdit) GetAddressOk() (*TenantAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *TenantEdit) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given TenantAddress and assigns it to the Address field.
func (o *TenantEdit) SetAddress(v TenantAddress) {
	o.Address = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *TenantEdit) GetContact() string {
	if o == nil || IsNil(o.Contact) {
		var ret string
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantEdit) GetContactOk() (*string, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *TenantEdit) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given string and assigns it to the Contact field.
func (o *TenantEdit) SetContact(v string) {
	o.Contact = &v
}

// GetDomainNames returns the DomainNames field value if set, zero value otherwise.
func (o *TenantEdit) GetDomainNames() []string {
	if o == nil || IsNil(o.DomainNames) {
		var ret []string
		return ret
	}
	return o.DomainNames
}

// GetDomainNamesOk returns a tuple with the DomainNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantEdit) GetDomainNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.DomainNames) {
		return nil, false
	}
	return o.DomainNames, true
}

// HasDomainNames returns a boolean if a field has been set.
func (o *TenantEdit) HasDomainNames() bool {
	if o != nil && !IsNil(o.DomainNames) {
		return true
	}

	return false
}

// SetDomainNames gets a reference to the given []string and assigns it to the DomainNames field.
func (o *TenantEdit) SetDomainNames(v []string) {
	o.DomainNames = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TenantEdit) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantEdit) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TenantEdit) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TenantEdit) SetName(v string) {
	o.Name = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *TenantEdit) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantEdit) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *TenantEdit) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *TenantEdit) SetPhone(v string) {
	o.Phone = &v
}

func (o TenantEdit) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantEdit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.DomainNames) {
		toSerialize["domain_names"] = o.DomainNames
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

type NullableTenantEdit struct {
	value *TenantEdit
	isSet bool
}

func (v NullableTenantEdit) Get() *TenantEdit {
	return v.value
}

func (v *NullableTenantEdit) Set(val *TenantEdit) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantEdit) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantEdit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantEdit(val *TenantEdit) *NullableTenantEdit {
	return &NullableTenantEdit{value: val, isSet: true}
}

func (v NullableTenantEdit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantEdit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
