/*
accent-auth

Accent's authentication service

API version: 0.1
Contact: help@accentvoice.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package auth

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GroupPut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupPut{}

// GroupPut struct for GroupPut
type GroupPut struct {
	Name string `json:"name"`
}

type _GroupPut GroupPut

// NewGroupPut instantiates a new GroupPut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupPut(name string) *GroupPut {
	this := GroupPut{}
	this.Name = name
	return &this
}

// NewGroupPutWithDefaults instantiates a new GroupPut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupPutWithDefaults() *GroupPut {
	this := GroupPut{}
	return &this
}

// GetName returns the Name field value
func (o *GroupPut) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GroupPut) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GroupPut) SetName(v string) {
	o.Name = v
}

func (o GroupPut) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupPut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *GroupPut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupPut := _GroupPut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupPut)

	if err != nil {
		return err
	}

	*o = GroupPut(varGroupPut)

	return err
}

type NullableGroupPut struct {
	value *GroupPut
	isSet bool
}

func (v NullableGroupPut) Get() *GroupPut {
	return v.value
}

func (v *NullableGroupPut) Set(val *GroupPut) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupPut) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupPut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupPut(val *GroupPut) *NullableGroupPut {
	return &NullableGroupPut{value: val, isSet: true}
}

func (v NullableGroupPut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupPut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
