/*
accent-auth

Testing EmailsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package auth

import (
	"context"
	openapiclient "github.com/ryanwclark1/accent-ui2/internal/client/auth"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_auth_EmailsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmailsAPIService GetEmailConfirm", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var emailUuid string

		httpRes, err := apiClient.EmailsAPI.GetEmailConfirm(context.Background(), emailUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailsAPIService GetNewEmailConfirmation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var userUuid string
		var emailUuid string

		httpRes, err := apiClient.EmailsAPI.GetNewEmailConfirmation(context.Background(), userUuid, emailUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailsAPIService PutEmailConfirm", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var emailUuid string

		httpRes, err := apiClient.EmailsAPI.PutEmailConfirm(context.Background(), emailUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailsAPIService UpdateAllUserEmails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var userUuid string

		httpRes, err := apiClient.EmailsAPI.UpdateAllUserEmails(context.Background(), userUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EmailsAPIService UpdateUserEmails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var userUuid string

		httpRes, err := apiClient.EmailsAPI.UpdateUserEmails(context.Background(), userUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
